application:
  rest:
    context-path: /api
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200, http://localhost:4201}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lothinphoneshop
    username: postgres
    password: lothinny
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#--------Connect with H2 Database----------
# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb
#     username: sa
#     password:
#   h2:
#     console:
#       enabled: true
#   jpa:
#     hibernate:
#       ddl-auto: create-drop
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.H2Dialect
#   jackson:
#     serialization:
#       fail-on-empty-beans: false

